### ISSUE TITLE
WooCommerce Integration?

### ISSUE THREAD

**Issue by amjad** [wpeverest/restaurantpress#1]
Hi, love the neat plugin. I was wondering if you are planning to do any WooCommerce integration for this plugin? And perhaps make it something like this: 

https://www.foodbooking.com/widget/menu?company_uid=cd6801cb-200c-495d-9b31-66637e177162

Fast and slick!

**Comment by shivapoudel** [comment]
Extension is live here: https://wpeverest.com/wordpress-plugins/restaurantpress/woocommerce-integration/
