### ISSUE TITLE
Database updater seems to have trouble while updating from 1.3.2 to 1.4.0

### ISSUE THREAD

**Issue by rabinstha** [wpeverest/restaurantpress#24]
Upon updating plugin from 1.3.2 to 1.4.0 , Run database updater is presented as notice.
Once it is clicked, your database is being updated notice doesn't seem to go away and the process of data transfer also doesn't seem to execute.
![edit menu item wp sandbox wordpress](https://user-images.githubusercontent.com/3048991/29916955-16fb2aaa-8e60-11e7-995f-19a18c207b92.png)

The price data doesn't seem to transfer as it should have been.

**Comment by shivapoudel** [comment]
This was fixed in master and was caused due to duplicate testing function existence. See fix: https://github.com/wpeverest/restaurantpress/commit/bfb7028e114eab12e72438c570b7ad2424e25ee7
