### ISSUE TITLE
Shows error while the category is deleted from the list

### ISSUE THREAD

**Issue by sanzeeb3** [wpeverest/restaurantpress#55]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of RestaurantPress on Github
- [x] I have attempted to find the simplest possible steps to reproduce the issue

## Steps to reproduce the issue

1. Create a category. Add items to the category.
2. Create a group. 
3. Group the created category into a group. 
4. Delete the created category.

## Expected/actual behavior

The syntax error:
`NOTICE: TRYING TO GET PROPERTY OF NON-OBJECT`
while trying to diplay menu in the frontend.

I was expecting to see a blank space in place of category items instead.

## Isolating the problem

- [ ] This bug happens with only RestaurantPress plugin active
- [ ] This bug happens with a default WordPress theme active, or [FoodHunt](https://themegrill.com/themes/foodhunt/)
- [x] I can reproduce this bug consistently using the steps above

**Comment by shivapoudel** [comment]
See #56
